In [1]:
import pandas as pd
import tensorflow as tf

In [27]:
df = pd.read_csv('jumsu.csv')
df

    공부시간   성적
0     10  100
1      9   95
2      9   98
3      8   88
4      9   92
5      7   77
6      5   60
7      8   88
8      9  100
9     10   90
10     5   50
11    10   95
12     9   80
13     5   40
14     1   30
15     2   20
16     4   55
17     2   20
18     6   60
19     7   70

In [36]:
x_data = list(df['공부시간'])
y_data = list(df['성적'])

In [37]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [38]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [39]:
hypothesis = W * X + b

In [48]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001) # 보통 0.001
train_op = optimizer.minimize(cost)

In [49]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [52]:
for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
    print(step, cost_val, sess.run(W), sess.run(b))

0 122.62404 [9.214364] [0.76338565]
1 110.999916 [9.312086] [0.778265]
2 101.75822 [9.399179] [0.7917953]
3 94.41066 [9.476798] [0.8041228]
4 88.56853 [9.545968] [0.8153778]
5 83.92326 [9.607606] [0.82567644]
6 80.229355 [9.662528] [0.8351224]
7 77.29173 [9.711462] [0.84380805]
8 74.955284 [9.755057] [0.8518157]
9 73.096794 [9.793893] [0.8592188]
10 71.61816 [9.8284855] [0.8660828]
11 70.44151 [9.859294] [0.8724661]
12 69.504944 [9.886729] [0.8784207]
13 68.7592 [9.911157] [0.883993]
14 68.16514 [9.932902] [0.8892244]
15 67.6917 [9.952257] [0.8941518]
16 67.3141 [9.9694805] [0.89880806]
17 67.01271 [9.984803] [0.90322244]
18 66.7719 [9.998431] [0.9074212]
19 66.57925 [10.010549] [0.9114275]
20 66.424866 [10.021318] [0.9152622]
21 66.30094 [10.030888] [0.9189439]
22 66.20119 [10.039386] [0.922489]
23 66.120674 [10.046929] [0.9259123]
24 66.055435 [10.053622] [0.92922693]
25 66.002365 [10.059556] [0.9324446]
26 65.95894 [10.064814] [0.93557566]
27 65.923195 [10.069468] [0.9386295]
28 65.89356 [10.073584] [0.94161445]
29 65.868805 [10.07722] [0.9445378]
30 65.847885 [10.080429] [0.9474063]
31 65.83003 [10.083258] [0.9502257]
32 65.81464 [10.085746] [0.95300126]
33 65.80117 [10.087932] [0.9557377]
34 65.78925 [10.089847] [0.9584392]
35 65.77855 [10.091521] [0.96110934]
36 65.768845 [10.092981] [0.96375155]
37 65.75988 [10.09425] [0.9663688]
38 65.75157 [10.095347] [0.9689637]
39 65.74375 [10.0962925] [0.97153854]
40 65.736305 [10.097102] [0.9740955]
41 65.72919 [10.097791] [0.97663647]
42 65.722305 [10.0983715] [0.979163]
43 65.71564 [10.098857] [0.98167664]
44 65.70912 [10.0992565] [0.9841787]
45 65.702736 [10.09958] [0.9866704]
46 65.69643 [10.099834] [0.9891527]
47 65.69022 [10.100029] [0.9916267]
48 65.684074 [10.100169] [0.99409306]
49 65.67799 [10.100261] [0.9965526]
50 65.67195 [10.100309] [0.999006]
51 65.66594 [10.10032] [1.0014538]
52 65.65994 [10.100296] [1.0038965]
53 65.65398 [10.100242] [1.0063347]
54 65.64804 [10.100161] [1.0087687]
55 65.642105 [10.100055] [1.011199]
56 65.63619 [10.099928] [1.0136259]
57 65.630295 [10.099782] [1.0160496]
58 65.6244 [10.099619] [1.0184704]
59 65.61851 [10.099441] [1.0208886]
60 65.61264 [10.099248] [1.0233043]
61 65.606766 [10.099044] [1.0257179]
62 65.6009 [10.098828] [1.0281293]
63 65.59504 [10.098603] [1.0305389]
64 65.58918 [10.09837] [1.0329467]
65 65.58333 [10.098129] [1.0353528]
66 65.577484 [10.097881] [1.0377574]
67 65.57164 [10.097628] [1.0401605]
68 65.5658 [10.097368] [1.0425622]
69 65.55996 [10.097104] [1.0449626]
70 65.55413 [10.096836] [1.0473619]
71 65.54831 [10.096564] [1.0497599]
72 65.542496 [10.096289] [1.0521567]
73 65.53668 [10.09601] [1.0545524]
74 65.530846 [10.09573] [1.0569472]
75 65.52504 [10.095447] [1.059341]
76 65.51924 [10.095161] [1.0617337]
77 65.51343 [10.094874] [1.0641255]
78 65.50763 [10.094585] [1.0665165]
79 65.501816 [10.0942955] [1.0689065]
80 65.49603 [10.094004] [1.0712957]
81 65.49022 [10.093711] [1.0736841]
82 65.48445 [10.093417] [1.0760716]
83 65.47866 [10.0931225] [1.0784583]
84 65.472885 [10.092827] [1.0808443]
85 65.467094 [10.092531] [1.0832294]
86 65.46132 [10.092235] [1.0856138]
87 65.45555 [10.091937] [1.0879974]
88 65.44978 [10.0916395] [1.0903803]
89 65.444016 [10.091341] [1.0927625]
90 65.43825 [10.0910425] [1.0951438]
91 65.432495 [10.090744] [1.0975244]
92 65.42674 [10.090445] [1.0999043]
93 65.421 [10.090145] [1.1022835]
94 65.415245 [10.089846] [1.104662]
95 65.409485 [10.089546] [1.1070397]
96 65.40375 [10.089247] [1.1094167]
97 65.39801 [10.088947] [1.111793]
98 65.39227 [10.088648] [1.1141686]
99 65.386536 [10.088347] [1.1165435]

In [53]:
sess.run(hypothesis, feed_dict={X: 3})

array([31.381584], dtype=float32)